<?php

require_once (dirname(__FILE__) . '/upload.php');

$debug = false;

$urls = array(

'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_01_Marinov_2012.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_02_Choong_Cheah_2013.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_03_Dow_Reels_2013.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_04_Marinov_Pikacha_2013.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_05_Marinov_Chinn_Edwards_Patrick_Patrick_2013.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_06_Dow_Reels_Butler_2013.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_07_Dow_Sivius_2014_small.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_08_Kalkman_Orr_2014.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_09_Dow_Reels_Ngiam_2015.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_10_Gassmann_2015.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_11_Marinov_2015_small.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_12_Garrison_et_al_2015.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_13_Phan_Dinh_2016.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_14_Dow_2016_small.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_15_Dow_et_al_2016_small.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_16_Dow_et_al_2016_small.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_17_Marinov_2016.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_18_Marinov_et_al_2016.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_19_Hamalainen_2107.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_20_Seehausen_2017_small.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_21_Choong_et_al_2017.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_22_Afendy_et_al_2017.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_23_Dow_et_al_2017_small.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_24_Dow_et_al_2018.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_25_Seehausen_et_al_2018.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_26_Marinov_et_al_2019.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_27_Dow_et_al_2019.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_28_Marinov_et_al_2019.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_29_Alfarisyi_2019.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_30_Reels_2019.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_31_Reels_2020.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_32_Farrell_Makbun_2020.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_33_da_Silva_Pinto_et_al_2020.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_34_Dow_corrections.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_35_Marinov_et_al_2021.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_36_Dow_et_al_2021.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_37_Dow_Choong_2021.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_38_Marinov_2022.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_39_Dow_et_al_2022.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_40_Marinov_2022.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_41_Marinov_Rashni_2023.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_42_Keetapithchayakul_et_al_2023.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/06/FSSEAPIO_43_Toan_2023.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/07/FSSEAPIO_44_Dow_Reels_2024.pdf',
'https://dragonflyfund.org/wp-content/uploads/2024/10/FSSEAPIO_45_Dow_2024.pdf',

'https://publikationen.ub.uni-frankfurt.de/opus4/frontdoor/deliver/index/docId/34815/file/kalkman_orr_2014_rhodothemis.pdf',
);

$urls = array('http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295123&attachType=lowqualitypdf');

$urls=array(

'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115183&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115360&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115116&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116565&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116521&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116070&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115567&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116044&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116055&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115540&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116131&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115618&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115631&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116141&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116151&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115644&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116101&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115608&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116120&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115940&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116467&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115954&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115967&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116479&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116427&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115920&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115931&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116003&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116018&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116030&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115981&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116505&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116324&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116334&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115828&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116346&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115798&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115878&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116384&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116396&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115889&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115376&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116356&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115842&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115859&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116199&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115688&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115701&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116212&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115655&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116161&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115666&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116176&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116188&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115676&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115750&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116259&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115765&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116273&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116227&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115715&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115724&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115736&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115050&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115061&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115071&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113478&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115022&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115037&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115081&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114922&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113384&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113398&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114934&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113357&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114900&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114911&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113371&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114981&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113455&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115004&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113466&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114949&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113428&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113439&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114971&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113252&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114786&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113263&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114797&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114811&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113273&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114758&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113221&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114771&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113245&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114853&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113316&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113326&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114867&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114879&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113341&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113287&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114827&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113299&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114843&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114658&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114668&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114687&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114627&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114643&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114721&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114730&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114743&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113201&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114700&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115486&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115495&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115301&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115131&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115459&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113409&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115284&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115210&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115447&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115225&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115140&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115433&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115237&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115422&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115389&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115472&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115312&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115323&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115402&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115149&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115196&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116404&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116550&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116284&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115097&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113187&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115530&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115906&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115162&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115897&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114710&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116297&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116308&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116085&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116244&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115341&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113419&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115261&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116534&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115174&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115780&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114960&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116413&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116443&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115516&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115815&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115595&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115581&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116492&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113213&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115506&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116454&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29116372&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113232&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115554&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29114991&attachType=lowqualitypdf',);

// to do, failed
$urls=array(
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115516&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29113409&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115116&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115131&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115140&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115149&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115162&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115174&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115183&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115196&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115210&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115225&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115237&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115261&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115284&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115301&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115312&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115323&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115341&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115360&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115389&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115402&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115422&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115433&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115447&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115459&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115472&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115486&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115495&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29115506&attachType=lowqualitypdf',
);

$urls=array(

'http://www.scdwzz.com/rc-pub/front/front-article/download?id=77883961&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=77883960&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=77884296&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=77884232&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=77884141&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=77884100&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=77884298&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=77884158&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=77884076&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=77884274&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=77883959&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=77884317&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=73222058&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=73222154&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=73222164&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=73222280&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=73222061&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=73222215&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=73222278&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=73222201&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=73222175&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=73222059&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=73222243&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66844806&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66844546&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66844547&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66844549&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66844751&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66844749&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66844705&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66844548&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66844804&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66844897&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66844753&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66844679&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66844550&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=59333203&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=59333172&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=59333318&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=59333316&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916362&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916328&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916343&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916510&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294624&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294627&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294623&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294474&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294563&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294562&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294580&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294606&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294399&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294438&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294416&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294418&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294392&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294852&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294868&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294975&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294970&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294775&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294783&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294723&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294741&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294835&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294983&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294928&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294800&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29294924&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295138&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295123&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295326&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295223&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295230&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295252&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295249&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295093&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295120&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295131&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295332&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295346&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295280&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295677&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295691&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295491&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295460&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295481&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295435&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295452&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295550&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295590&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295605&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295574&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295657&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295683&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295790&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295751&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295846&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295916&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295929&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295872&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295791&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295822&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295932&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295948&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295967&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29295974&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29296054&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29296057&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29296325&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29296185&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29296159&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29296316&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29296267&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29296287&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29296169&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29296078&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29296186&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29296070&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29340068&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29340077&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29340033&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29340062&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29340199&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29340170&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29340171&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29340287&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29340293&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29340198&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29340200&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29340267&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29340274&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29340071&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29297466&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29297421&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29297493&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29297499&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29297405&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29297403&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29297349&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29297370&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29297237&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29297381&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29297254&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29297265&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29297233&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29297264&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29306542&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29306297&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29306254&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29306261&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29306364&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29306407&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29306397&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29306258&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29306320&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29306524&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29306527&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29306410&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29306420&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29306509&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29341345&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29341373&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29341326&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29341409&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29341235&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29341300&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29341228&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29341196&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29341194&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29341214&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29341417&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29341431&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29341426&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29308789&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29308758&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29308857&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29308893&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29308962&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29308997&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309010&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309017&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29308877&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29308885&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29308790&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29308746&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29308757&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29338336&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29338288&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29338245&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29338267&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29338222&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29338234&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29338596&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29338502&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29338431&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29338375&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29338381&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29338493&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29338447&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29337766&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29337784&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29337796&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29337629&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29337675&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29337949&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29337894&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29337912&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29337913&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29337869&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29337927&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29337761&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29337666&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29337679&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309350&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309317&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309238&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309215&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309284&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309265&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309118&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309168&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309125&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309133&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309140&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309374&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309385&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=29309393&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=59333144&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=59333420&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=59333247&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=59333397&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=59333156&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=59333418&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=59333146&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=53948539&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=53948406&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=53948622&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=53948538&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=53948520&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=53948549&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=53948624&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=53948767&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=53948664&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=53948666&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=53948769&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=53948405&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=53948615&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66931853&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66931855&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=48436455&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=48436612&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=48436580&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=48436747&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=48436639&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=48436457&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=48436584&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=48436586&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=48436454&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=48436582&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=48436749&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=48436456&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=44467632&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=44467586&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=44467393&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=44467391&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=44467615&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=44467392&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=44467511&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=44467390&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=66931851&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=44467613&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=44467394&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=44467515&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=44467513&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=42344375&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=42344360&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=42344392&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=42344266&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=42344263&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=42344569&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=42344265&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=42344267&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=42344570&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=42344592&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=42344542&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=42344264&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=42344566&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=42344497&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37875150&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=40356255&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37875177&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=40356272&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=40356247&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=40356434&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=40356419&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=40356223&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=40356342&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=40356309&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=40356519&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=40356493&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=40356481&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37848603&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37848884&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37848563&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37848724&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37848649&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37848638&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37848826&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37848732&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37848761&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37848683&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37848817&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37848524&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=37848847&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=35722294&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=35722446&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=35722183&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=35722327&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=35722129&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=35722391&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=35722483&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=35722219&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=35722262&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=35722567&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=35722453&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=35722360&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=35722538&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=33640582&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=33640849&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=33640835&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=33640677&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=33640556&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=33640634&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=33640647&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=33640714&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=33640784&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=33640657&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=33640899&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=33640802&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=33640794&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=32385738&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=32385679&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=32385863&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=32385598&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=32385794&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=32385769&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=32385896&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=32385612&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=32385836&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=32385710&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=32385814&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=32385702&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=30968488&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=30968493&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=30968399&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=30968579&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=30968377&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=30968320&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=27666255&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=30968312&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=30968253&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=30968188&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=30968450&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=30968441&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=30968342&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=27662933&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=27666349&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28440559&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=27666288&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=27666318&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=27665797&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=27896634&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28440583&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=27894910&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=27666370&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=27665769&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=27666402&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=27873999&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=27665901&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916384&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916411&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916453&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916433&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916490&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916468&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916268&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916239&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916252&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916291&attachType=lowqualitypdf',
'http://www.scdwzz.com/rc-pub/front/front-article/download?id=28916311&attachType=lowqualitypdf',
);

$urls=array(
'http://hbs.bpbmwebdata.org/pubs-online/pdf/b189p11-103.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-121.pdf',

'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-109.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-111.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-115.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-119.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-121.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-127.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-13.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-131.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-135.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-143.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-149.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-21.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-25.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-29.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-3.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-3.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-35.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-39.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-51.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-53.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-57.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-67.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-71.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-75.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-81.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-85.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-87.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-91.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-93.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-95.pdf',
'http://hbs.bpbmwebdata.org/pubs-online/pdf/bull113-97.pdf',

);

$urls=array();

//$urls=array('https://www.aemnp.eu/data/article-1484/1465-53_2_821.pdf');

$urls=array('http://hbs.bpbmwebdata.org/pi/pdf/3(2)-203-222.pdf');

$urls=array(
'https://repositorio.inpa.gov.br/bitstream/1/3115/1/pibic_inpa.pdf',
'https://dialnet.unirioja.es/descarga/articulo/9138278.pdf',
'https://sammlungen.ub.uni-frankfurt.de/download/pdf/10807144.pdf',
'http://bionames.org/sha1/8adbcfb47fdd23ea372983d75a54561abb8bfb07',

'http://publ.moth.jp/tinea/tinea24-4.pdf',
);

$force = false;
//$force = true;

$parse_pdf = true; // default, will fail if PDF has problems
//$parse_pdf = false; // don't attempt to parse the PDF, use if PDFs are a bit ropey

foreach ($urls as $url)
{
	echo "\nurl=$url\n";
	
	if (preg_match('/^10\.\d+/', $url))
	{
		$url = 'https://doi.org/' . $url;
	}
	
	$go = true;
	
	if (source_url_in_db($url) && !$force)
	{
		//echo "Have $url already\n";
		$go = false;
	}
	
	if ($go)
	{
		$source = get_source_details($url, '', true, $debug);	
	
		$source->content_filename = get_filename_from_url($url, 'pdf');	
		
		if (isset($source->{'content-disposition'}))
		{
			// this may cause problems if name has bad character encoding
			$content_disposition = $source->{'content-disposition'};
			
			$source->content_filename = sanitise_filename($content_disposition);
			if (!preg_match('/\.pdf$/i', $source->content_filename))
			{
				$source->content_filename .= '.pdf';
			}
		}
		
		$source->content_filename = $config['tmp'] . '/' . $source->content_filename;
			
		if (1)
		{
			$source->url = str_replace("'", "%27", $source->url);
				
			// -k to override bad certificates
			// --max-time for slow connections
			$command = "curl --max-time 1024 -k -L --user-agent \"Mozilla/5.0 (Linux; Android 10; SM-G996U Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Mobile Safari/537.36\" -o '$source->content_filename' '$source->url'";
		}
		else
		{
			$command = "curl_chrome116 -k -L  -o '$source->content_filename' '$source->url'";

			/*
			$command = "'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'"
				. "  --headless --disable-gpu --dump-dom"
				. " --user-agent=\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.50 Safari/537.36\""
				. " '" . $source->url . "'"
				. ' > ' . $source->content_filename;
			*/
		}
		echo $command . "\n";
		
		system($command, $result_code);
		
		// check OK
		if ($result_code == 0)
		{
			$source->url = str_replace("%27", "'", $source->url);
			store_pdf($source, $parse_pdf, $debug);
		}
		
		$rand = rand(500000, 1000000);
		echo "\n-- ...sleeping for " . round(($rand / 1000000),2) . ' seconds' . "\n\n";
		usleep($rand);
	}
}

?>
